exclude: '.git|setup.cfg|migrations|manage.py|venv'
default_stages: [commit]

repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: migrations
        name: check migrations
        entry: python3 manage.py makemigrations --check --dry-run
        language: system
        always_run: true
        pass_filenames: false
        fail_fast: true
        stages:
        - push

      - id: tests
        name: run tests
        entry: python3 manage.py test
        language: system
        always_run: true
        pass_filenames: false
        stages:
        - push
