# Generated by Django 4.1.1 on 2022-11-04 15:24

from django.db import migrations


def create_users(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    User = apps.get_model("accounts", "User")

    User.objects.create(
        email="alex.smith@example.com",
        first_name="Alex",
        last_name="Smith",
        is_active=True,
        admin=True,
        password="pbkdf2_sha256$390000$FB1xFN58olQ6EgRgwRpXq0$MTCM0WIyGPvgH8kl4/kAmpduf+FWpNAr4uqiJjKb8Rw=",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_users),
    ]
