# Generated by Django 4.1.1 on 2022-11-15 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("parentwsp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="message")),
                (
                    "chat_name",
                    models.CharField(max_length=255, verbose_name="chat name"),
                ),
                ("sender", models.CharField(max_length=255, verbose_name="sender")),
                (
                    "sender_number",
                    models.CharField(max_length=255, verbose_name="sende number"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="parentwsp.session",
                        verbose_name="session",
                    ),
                ),
            ],
        ),
    ]
