# Generated by Django 4.1.1 on 2022-12-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parentwsp", "0002_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="status",
            field=models.CharField(
                choices=[("connected", "Connected"), ("disconnected", "Disconnected")],
                default="connected",
                max_length=255,
                verbose_name="estado",
            ),
        ),
    ]
