# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install pre-commit hooks
      run: |
        sh install-pre-commit.sh
    - name: Run pre-commit hooks
      run: |
        pre-commit run -a --hook-stage commit
    - name: Run pre-push hooks
      run: |
        pre-commit run -a --hook-stage push
    - name: Run tests
      run: |
        python3 manage.py test
